import { useTexture } from '@react-three/drei';
import type { RapierRigidBody } from '@react-three/rapier';
import { Object3D } from 'three';
import { useTireTracksLogic } from '@/hooks/useTireTracksLogic';
import { MAX_TRACKS, TRACK_COLOR } from '@/config/particles';

interface TireTracksProps {
  wheelsRef: React.RefObject<(Object3D | null)[]>;
  chassisRef: React.RefObject<RapierRigidBody | null>;
}

export function TireTracks({ wheelsRef, chassisRef }: TireTracksProps) {
  // Load the external texture generated by AI
  const trackTexture = useTexture('/textures/tire_track.png');
  
  // Use the extracted logic hook
  const { meshRef, opacityArray } = useTireTracksLogic(wheelsRef, chassisRef);

  return (
    <instancedMesh ref={meshRef} args={[undefined, undefined, MAX_TRACKS]} frustumCulled={false}>
      <planeGeometry args={[1, 1]}>
        <instancedBufferAttribute
          attach="attributes-instanceOpacity"
          args={[opacityArray, 1]}
        />
      </planeGeometry>
      <meshBasicMaterial
        transparent
        depthWrite={false}
        map={trackTexture}
        polygonOffset={true}
        polygonOffsetFactor={-10}
        polygonOffsetUnits={-10}
        color={TRACK_COLOR}
        opacity={1} // Base opacity handled by attribute
        onBeforeCompile={(shader) => {
          shader.vertexShader = `
            attribute float instanceOpacity;
            varying float vInstanceOpacity;
            ${shader.vertexShader}
          `.replace(
            `#include <begin_vertex>`,
            `#include <begin_vertex>
             vInstanceOpacity = instanceOpacity;`
          );
          shader.fragmentShader = `
            varying float vInstanceOpacity;
            ${shader.fragmentShader}
          `.replace(
            `vec4 diffuseColor = vec4( diffuse, opacity );`,
            `vec4 diffuseColor = vec4( diffuse, opacity * vInstanceOpacity );`
          );
        }}
      />
    </instancedMesh>
  );
}
