import type { TireConfig, SurfaceType } from './vehicle';

/**
 * Visual particle properties generated by wheels on this surface.
 */
export interface SurfaceParticleConfig {
  /** Hex color or CSS color string for dust/smoke */
  readonly color: string;
  /** Size multiplier for particles emitted on this surface */
  readonly scale: number;
  /** Lifetime in seconds */
  readonly lifetime: number;
  /** Multiplier for particle emission rate */
  readonly emitRateMultiplier: number;
}

/**
 * Audio characteristics of the surface.
 */
export interface SurfaceAudioConfig {
  /** Sound type category for rolling sound */
  readonly soundType: 'grass' | 'mud' | 'gravel' | 'asphalt' | 'sand';
  /** Base pitch for rolling audio loop */
  readonly basePitch: number;
  /** Volume multiplier */
  readonly volumeMultiplier: number;
}

/**
 * Complete definition of a terrain surface, unifying tire physics,
 * visual particle effects, and audio characteristics.
 */
export interface SurfaceDefinition {
  /** Unique surface identifier */
  readonly id: SurfaceType;
  /** Human-readable display name */
  readonly name: string;
  /** Friction and grip curve for front and rear tires */
  readonly tireModel: TireConfig;
  /** Visual particle configuration */
  readonly particles: SurfaceParticleConfig;
  /** Audio configuration */
  readonly audio: SurfaceAudioConfig;
  /** Tire track mark darkness (0.0 = invisible, 1.0 = pitch black) */
  readonly skidMarkOpacity: number;
}
