import type { CSSProperties } from 'react';

export function formatLapTime(seconds: number): string {
  if (seconds <= 0) return '00:00.00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  const millis = Math.floor((seconds % 1) * 100);
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}.${millis.toString().padStart(2, '0')}`;
}

export function getFocusStyle(isFocused: boolean): CSSProperties {
  if (!isFocused) return {};
  return {
    borderColor: '#E31837',
    background: 'linear-gradient(90deg, rgba(227, 24, 55, 0.22) 0%, rgba(27, 54, 93, 0.16) 100%)',
    boxShadow: '0 0 0 1px #E31837, 0 6px 20px rgba(227, 24, 55, 0.35)',
    transform: 'translateX(6px)',
    color: '#FFFFFF',
    zIndex: 3,
    transition: 'transform 0.14s cubic-bezier(0.16, 1, 0.3, 1), box-shadow 0.14s ease, background 0.14s ease, border-color 0.14s ease',
  };
}


export const menuStyles: Record<string, CSSProperties> = {
  overlayMenu: {
    position: 'absolute',
    inset: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundImage: `
      linear-gradient(135deg, rgba(6, 9, 16, 0.94) 0%, rgba(10, 14, 25, 0.88) 45%, rgba(6, 9, 16, 0.94) 100%),
      radial-gradient(ellipse at 40% 30%, rgba(227, 24, 55, 0.12) 0%, transparent 60%),
      url('/images/ui/rally_backdrop.jpg')
    `,
    backgroundSize: '100% 100%, 100% 100%, cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: '#F1F5F9',
    overflowY: 'auto',
    padding: 'calc(8px + var(--sat)) calc(16px + var(--sar)) calc(8px + var(--sab)) calc(16px + var(--sal))',
    boxSizing: 'border-box',
  },
  mainOverlayMenu: {
    position: 'absolute',
    inset: 0,
    zIndex: 50,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    backgroundImage: `
      linear-gradient(to right, rgba(6, 9, 16, 0.95) 0%, rgba(6, 9, 16, 0.88) 380px, rgba(6, 9, 16, 0.3) 580px, transparent 850px),
      linear-gradient(to top, rgba(6, 9, 16, 0.7) 0%, transparent 100px)
    `,
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: '#F1F5F9',
    overflowY: 'auto',
    padding: 'calc(16px + var(--sat)) calc(24px + var(--sar)) calc(12px + var(--sab)) calc(24px + var(--sal))',
    boxSizing: 'border-box',
    pointerEvents: 'auto',
  },
  mainCardMenu: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: '1240px',
    margin: 'auto 0',
    alignItems: 'flex-start',
    gap: '12px',
    boxSizing: 'border-box',
    pointerEvents: 'auto',
  },
  mainNavColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    width: '100%',
    maxWidth: '380px',
  },
  pauseOverlayMenu: {
    position: 'absolute',
    inset: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'radial-gradient(circle at center, rgba(15, 23, 42, 0.75) 0%, rgba(5, 8, 15, 0.92) 100%)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: '#F1F5F9',
    overflowY: 'auto',
    padding: 'calc(8px + var(--sat)) calc(16px + var(--sar)) calc(8px + var(--sab)) calc(16px + var(--sal))',
    boxSizing: 'border-box',
  },
  cardMenu: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: '1240px',
    gap: '16px',
    margin: 'auto',
  },
  pauseCardMenu: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: '520px',
    padding: '22px 24px 16px 24px',
    gap: '12px',
    margin: 'auto',
    boxSizing: 'border-box',
    background: 'linear-gradient(180deg, rgba(20, 28, 45, 0.95) 0%, rgba(11, 16, 28, 0.98) 100%)',
    border: '1px solid rgba(255, 255, 255, 0.12)',
    borderRadius: '18px',
    boxShadow: '0 24px 60px rgba(0, 0, 0, 0.7), 0 0 0 1px rgba(227, 24, 55, 0.25)',
  },
  dashboardLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(340px, 420px) 1fr',
    gap: '40px',
    width: '100%',
    alignItems: 'start',
  },
  logoContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '8px',
  },
  logoImage: {
    maxWidth: '340px',
    maxHeight: '140px',
    objectFit: 'contain',
    filter: 'drop-shadow(0 6px 20px rgba(0, 0, 0, 0.6))',
  },
  pauseTitle: {
    fontSize: '26px',
    fontWeight: 800,
    letterSpacing: '4px',
    margin: '0 0 4px 0',
    color: '#F1F5F9',
    textTransform: 'uppercase',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  subtitle: {
    fontSize: '13px',
    marginBottom: '16px',
    fontWeight: 500,
    letterSpacing: '0.5px',
    color: '#94A3B8',
  },
  buttonGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    width: '100%',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 18px',
    minHeight: '44px',
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.03)',
    color: '#F1F5F9',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s cubic-bezier(0.16, 1, 0.3, 1)',
    outline: 'none',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.25)',
    letterSpacing: '0.5px',
    position: 'relative',
    overflow: 'hidden',
    textAlign: 'left',
    boxSizing: 'border-box',
    touchAction: 'manipulation',
  },
  primaryButton: {
    background: 'linear-gradient(90deg, #991B1B 0%, #E31837 50%, #B91C1C 100%)',
    border: '1px solid rgba(255, 255, 255, 0.25)',
    color: '#FFFFFF',
    fontWeight: 700,
    boxShadow: '0 4px 20px rgba(227, 24, 55, 0.45)',
  },
  secondaryButton: {
    background: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  modeCard: {
    padding: '20px',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(255, 255, 255, 0.02)',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.2s ease',
  },
  modeBadge: {
    padding: '3px 8px',
    borderRadius: '4px',
    color: '#fff',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.5px',
  },
  tabContainer: {
    display: 'flex',
    gap: '8px',
    width: '100%',
    marginBottom: '10px',
  },
  tabButton: {
    flex: 1,
    minHeight: '44px',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(255, 255, 255, 0.04)',
    color: '#94A3B8',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    touchAction: 'manipulation',
    boxSizing: 'border-box',
  },
  activeTabButton: {
    background: 'linear-gradient(90deg, #1B365D, #E31837)',
    color: '#FFFFFF',
    borderColor: 'rgba(255, 255, 255, 0.3)',
    boxShadow: '0 2px 10px rgba(227, 24, 55, 0.3)',
  },
  garageDetails: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    marginTop: '12px',
  },
  garageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  garageVehicleName: {
    fontSize: '18px',
    fontWeight: 700,
    color: '#F1F5F9',
  },
  driveBadge: {
    padding: '4px 10px',
    borderRadius: '6px',
    background: '#E31837',
    color: '#fff',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.5px',
  },
  statsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  statRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '12px',
    fontWeight: 600,
  },
  statLabel: {
    width: '90px',
    color: '#94A3B8',
  },
  statTrack: {
    flex: 1,
    height: '6px',
    borderRadius: '3px',
    background: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  statFill: {
    height: '100%',
    borderRadius: '3px',
    background: 'linear-gradient(90deg, #3B82F6, #E31837)',
  },
  statValue: {
    width: '32px',
    textAlign: 'right',
    color: '#F1F5F9',
  },
  trackCard: {
    padding: '14px 18px',
    borderRadius: '10px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    background: 'rgba(255, 255, 255, 0.03)',
    display: 'flex',
    flexDirection: 'column',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  difficultyBadge: {
    padding: '2px 8px',
    borderRadius: '4px',
    color: '#fff',
    fontSize: '11px',
    fontWeight: 700,
  },
  controlsHelp: {
    width: '100%',
    borderRadius: '12px',
    padding: '20px',
    fontSize: '13px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
  },
  controlRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 0,
  },
  subView: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: '920px',
    maxHeight: 'calc(100dvh - var(--sat) - var(--sab) - 16px)',
    gap: '10px',
    alignItems: 'center',
    padding: '12px 20px',
    background: 'linear-gradient(180deg, rgba(20, 28, 44, 0.94) 0%, rgba(11, 16, 26, 0.97) 100%)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '16px',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.6)',
    boxSizing: 'border-box',
    margin: 'auto',
    overflowY: 'auto',
  },
  subViewTitle: {
    margin: '0 0 8px 0',
    fontSize: '20px',
    fontWeight: 700,
    letterSpacing: '1px',
    color: '#F1F5F9',
    textTransform: 'uppercase',
  },
  optionRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    minHeight: '44px',
    padding: '8px 16px',
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#E2E8F0',
    boxSizing: 'border-box',
  },
  select: {
    padding: '8px 14px',
    minHeight: '44px',
    borderRadius: '6px',
    background: '#1A2234',
    color: '#F1F5F9',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    outline: 'none',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    touchAction: 'manipulation',
    boxSizing: 'border-box',
  },
  checkbox: {
    width: '24px',
    height: '24px',
    minWidth: '44px',
    minHeight: '44px',
    cursor: 'pointer',
    accentColor: '#E31837',
    touchAction: 'manipulation',
  },
  gamepadStatusBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    width: '100%',
    padding: '10px 14px',
    borderRadius: '8px',
    marginBottom: '6px',
    fontSize: '13px',
    color: '#E2E8F0',
    boxSizing: 'border-box',
  },
  gamepadNavFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '16px',
    width: '100%',
    padding: '12px 18px',
    marginTop: '12px',
    background: 'rgba(15, 23, 42, 0.7)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '12px',
    fontSize: '12px',
    color: '#94A3B8',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
  },
  pauseGamepadNavFooter: {
    background: 'transparent',
    border: 'none',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: 0,
    padding: '12px 4px 0 4px',
    marginTop: '0px',
    gap: '8px',
  },
};
